name: 定时更新上游源码

on:
  schedule:
  - cron: "30 1 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@master
      with:
        source_repo: "https://github.com/gogf/gf.git"
        source_branch: "master"
        sync_tags: "true"
        destination_branch: "upstream"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: tgymnich/fork-sync@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        head: upstream
        merge_method: rebase
